wget -nc http://img.bulawayo24.com/articles/SA_speed.jpg

wget -nc  http://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Max_Nordau.jpg/220px-Max_Nordau.jpg
wget -nc  http://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Max_reger_1.jpg/220px-Max_reger_1.jpg
wget -nc  http://www.abortmag.com/abortpegs/maxy.jpg
wget -nc  http://en.louloumagazine.com/wp-content/uploads/2012/10/Max-Mara-bbt-F12-018-300x420.jpg
wget -nc  http://www.spacecast.com/getattachment/e7aba951-e5f5-4c13-8cf5-68770ddb3659/Bedlam/Cast/Max.aspx
wget -nc  http://media.comicvine.com/uploads/7/78207/2252545-mad_max_the_road_warrior_1.jpg
wget -nc  http://maxandruby.treehousetv.com/content/assets/en-ca/characters/max/max1.png
wget -nc  http://www.straight.com/files/images/wide/MOV_MaxManus_2206.jpg
wget -nc  https://images-na.ssl-images-amazon.com/images/G/01/videogames/detail-page/max.payne.3.01.lg.jpg
wget -nc  http://www.fredgodfreysongs.ca/Collaborators/Images/Max_Miller.jpg
wget -nc  http://tenpackbmx.com/wordpress/wp-content/uploads/2010/04/max2.jpg
wget -nc  http://www.greenfieldguitars.com/common/sitemedia/MaxRoest1.JPG
wget -nc  http://i.huffpost.com/gen/677124/thumbs/r-LOTTO-MAX-JACKPOT-APRIL-6-2012-large570.jpg?11
wget -nc  http://upload.wikimedia.org/wikipedia/commons/d/df/Max_Planck_1901.GIF
wget -nc  http://churches.worldvision.ca/wp-content/uploads/2012/06/Max-Lucado.jpg
wget -nc  http://upload.wikimedia.org/wikipedia/commons/d/d7/Max_planck.jpg
wget -nc  http://bitcast-r.v1.iad1.bitgravity.com/myyoga/open/images/publishers/medium/146-max-strom.jpg
wget -nc  http://piknicelectronik.com/sites/site-1/assets/Max_Reynold_s.jpg?1304434322
wget -nc  https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIp_Y9-DX2gbkwnHI_FIh9HVv5E66T5ipLFnNhf14W15sA5BjEuQ
wget -nc  http://www.paliareroland.com/images/people/max_starnino_3.jpg?sfvrsn=2
wget -nc  http://blog.muchmusic.com/wp-content/uploads/2012/04/Max-George.jpg
wget -nc  http://www.alexramon.com/images/photos3/07-01-max-kerman-arkells.jpg
wget -nc  http://www.silentfilmstars.net/wp-content/uploads/2012/02/Max_Linder.jpg
wget -nc  http://laurelrusswurm.files.wordpress.com/2009/09/max.jpg
wget -nc  http://www.wittenlaw.com/public/uploads/contacts/Max_Cropped/300w_Max_Cropped.jpg
wget -nc  http://www.24hourrelay.com/upload/images/vancouver/Entertainment/Max%20Tell%20Head%20Shot.jpg
wget -nc  http://beta.images.theglobeandmail.com/144/incoming/article4185917.ece/ALTERNATES/w620/wMax-Payne-3-4.jpg
wget -nc  http://maxfraser.ca/images/Portrait_max_280x383.jpg
wget -nc  https://bcchf.ca/assets/Uploads/_resampled/SetRatioSize480360-2011StoriesFeaturePhotoMaxRoutley.jpg
wget -nc  http://upload.wikimedia.org/wikipedia/commons/8/89/Friedrich_Max_M%C3%BCller,_1898.jpg
wget -nc  http://www.mbtw.com/media/images/profiles/lazo_max.jpg
wget -nc  http://www.concordia.ca/campus-life/arts-and-culture/max-stern/images/max-stern.jpg
wget -nc  http://www.cbc.ca/gfx/images/sports/photos/2012/10/10/scherzer-max_940-8col.jpg
wget -nc  http://www.adera.com/wp-content/uploads/2012/09/max_banner.jpg
wget -nc  http://www.ftape.com/media/wp-content/uploads/2010/01/MaxHurd05.jpg
wget -nc  http://hockey.dobbersports.com/dobberpics/MaxPacioretty.jpg
